version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-genius
    environment:
      MYSQL_ROOT_PASSWORD: changeme
      MYSQL_DATABASE: genius_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: changeme
    ports:
      - "3306:3306"
    volumes:
      - /var/lib/mysql
